feature: update single source endpoint
Energy-Price-News-API/energy-prices-api pull request #172
Opened 2022-10-01 20:35 UTC by chinmaykumbhare

## What type of PR is this? (check all applicable)

- [ :white_check_mark:] 💡 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test

## Description

## Fixes #168 

## Screenshots (if appropriate)

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 🙅 no documentation needed

2022-10-01 21:10 UTC, MizouziE commented on src/controller/api/newsAPIController.js
> +    const sourceId = (req.params.sourceId).toLowerCase();
Good thinking! :raised_hands:

2022-10-01 21:11 UTC, MizouziE commented on src/middlewares/existingSourceMiddleware.js
> +  const sourceId = (req.params.sourceId).toLowerCase();
:star2:

2022-10-01 21:13 UTC, MizouziE approved these changes
Well done catching the overlooked potential pitfall of case sensitivity!

2022-10-01 21:23 UTC, MizouziE requested changes
I have just realised that this gives cause for some documentation editing. 

in `API_DOCS.md` please change the following section:

![image](https://user-images.githubusercontent.com/90829439/193428701-9f04e4fe-92b6-46f8-848e-85f2eaae16b5.png)

You can change it as you see fit or use the following to replace the corresponding lines ~52:

```
### Articles by single source

[/api/news/sources/{source}](http://localhost:8000/api/news/sources/skynews)

These endpoints use the name of a single news source to retrieve **only the articles from that particular news source**. In the example above it will show for Sky News, but any of the avaiable sources can be used.

> **Note**
> The name of the source must have spaces omitted, otherwise it will return a 404 error.

```

2022-10-02 13:08 UTC, chinmaykumbhare commented
have made the requested changes @MizouziE

2022-10-02 14:02 UTC, MizouziE approved these changes
Perfect. Thank you very much! 🙏

2022-10-02 14:02 UTC, merged