Added Pagination Tests
Energy-Price-News-API/energy-prices-api pull request #202
Opened 2022-10-14 14:51 UTC by MuminAhmadKhan

Added Test for pagination functionality

2022-10-14 18:34 UTC, MizouziE requested changes
The actual tests are great and I see in the CI that they all pass so :+1: :+1: 

Just a tiny little bit of tidy up and it's good to go.

Thanks for writing these! :pray:

2022-10-14 18:34 UTC, MizouziE commented on __mocks__/mockarticles.js
> +            },
The formatting is a little weird in this file **BUT** it is still valid JSON so I shouldn't complain. :sweat_smile:

2022-10-14 18:34 UTC, MizouziE commented on __tests__/unit-tests/paginate.test.js
> +       // console.log(value)
Also this one, thanks!

2022-10-15 02:26 UTC, MuminAhmadKhan commented on __tests__/unit-tests/paginate.test.js
> +        //console.log(value)
This test or just the console.log?

2022-10-15 06:23 UTC, MizouziE commented on __tests__/unit-tests/paginate.test.js
> +        //console.log(value)
Just the console.log()

The tests are good.

2022-10-15 06:43 UTC, MuminAhmadKhan commented on __tests__/unit-tests/paginate.test.js
> +        //console.log(value)
Thanks for the feedback and sorry for such silly mistakes.
Please check now.

2022-10-15 09:10 UTC, MizouziE approved these changes
Thanks!

2022-10-15 09:10 UTC, merged